### ISSUE TITLE
Feature request: Basic Auth

### ISSUE THREAD

**Issue by jbenguira** [shieldoo/shieldoo-mesh-docker-compose#1]
Hello,
most of the time there is a single admin managing all the networks, it's a PITA to create Azure or Google apps when all you need is a single user ... 

Would you consider adding a basic auth / no auth / or a simple user system instead of forcing to use a third party auth system?

**Comment by valda-z** [comment]
It is not on roadmap now because this authentication is also used for users in shieldoo network and there is MS or google auth most secure way.
But lets leave issue open for while - we will think about this ..

**Comment by jbenguira** [comment]
> It is not on roadmap now because this authentication is also used for users in shieldoo network and there is MS or google auth most secure way. But lets leave issue open for while - we will think about this ..


FYI using a third party for auth means when the third party is down you are down, when the third party decide to kill your account for no reason ... your app and all your users are down as well, there are tons of horrors story about Google deciding to ban an account because of a false detection by an AI system with absolutely no recourse.
Best is to selfhost everything and not relying on third parties.

In an ideal world, keep it simple with with a login/password than can be set in env vars, this will be a lot easier to deploy and use for 99% of us, the 1% that still want to use Azure or Google can do it with env var configuration

Thanks for considering this :)

**Comment by valda-z** [comment]
Fixed by pull request: https://github.com/shieldoo/shieldoo-mesh-docker-compose/pull/2
